services:
  stream-stack:
    image: directstreamer:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BACKEND_IP=${BACKEND_IP}
        - BACKEND_PORT=${BACKEND_PORT}
        - RELEASE=${RELEASE}
    container_name: direct-streamer
    cap_add:
      - SYS_NICE
    command: >
      /bin/sh -c "nice -10 /app/server & (while true; do /app/adb_manager.sh; sleep 2; done) & wait -n"
    ports:
      - "${BACKEND_IP}:${HOST_PORT}:${BACKEND_PORT}"
    volumes:
      - ${MEDIA_VOLUME}:/media:ro
      - ./ds-store:/ds-data
      - ./ds-store:/root/.android
    environment:
      - PORT=${BACKEND_PORT}
      - BACKEND_IP=${BACKEND_IP}
      - MEDIA_DIR=/media
      - TZ=${TZ}
    restart: unless-stopped
